export const ERROR_CODE = {
  UNKNOWN: 'UNKNOWN',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  DUPLICATE_KEY: 'DUPLICATE_KEY',
  IMAGE_ASPECT_RATIO_SIZE_INVALID: 'IMAGE_ASPECT_RATIO_SIZE_INVALID',
  IMAGE_ASPECT_RATIO_INVALID: 'IMAGE_ASPECT_RATIO_INVALID',
  HIGHT_IMAGE_INVALID: 'HIGHT_IMAGE_INVALID',
  WIDTH_IMAGE_INVALID: 'WIDTH_IMAGE_INVALID',
  MAX_SIZE_FILE_INVALID: 'MAX_SIZE_FILE_INVALID',
  TYPE_FILE_INVALID: 'TYPE_FILE_INVALID',
} as const;

export type ErrorCode = keyof typeof ERROR_CODE;
export type ErrorCodeValues = (typeof ERROR_CODE)[ErrorCode];
